theme: jekyll-theme-minimal

# Site wide configuration

title: Joseph Fogarty's Website
locale: en_US
#logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Joseph Fogarty
  #avatar: #bio-photo.jpg
  #bio: #"This is a sample Jekyll academic website."
  email: jjf1295@gmail.com
  # Do not include the @ symbol in your Twitter username
  #twitter: #username
  #linkedin: #username
  github: josephfogarty
  #orcid: # ID Number (ex. 0000-0000-0000-0000)
  #researchgate: #username
  #mendeley: #username
  #google:
    #plus: #username
    #analytics:
    #verify:
    #scholar: #id
